# 定义共享的环境变量块
x-shared-env: &shared-env
  TZ: Asia/Shanghai

# 定义网络
networks:
  hata-network:
    name: ${CONTAINER_PREFIX}-network
    ipam:
      driver: default
      config:
        - subnet: 10.100.100.0/24  # 指定一个未被占用的子网

services:
  hata-postgresql:
    image: postgres:15
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRESQL_ROOT_NAME}           # 自定义用户名
      POSTGRES_PASSWORD: ${POSTGRESQL_ROOT_PASSWORD}   # 自定义密码
      POSTGRES_DB: "hata-service-platform"         # 自定义数据库名
      LANG: "C.UTF-8"
    volumes:
      - ./postgre-data:/var/lib/postgresql/data
    networks:
      - hata-network 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s

  hata-redis:
    container_name: ${CONTAINER_PREFIX}-redis
    # 1. 放弃自定义构建（删除 build 块），改用 7.2 稳定版镜像
    image: redis:7.2-alpine
    ports:
      - "${REDIS_PORT}:8761"
    volumes:
      # 2. 保留你原有的配置文件挂载（用精简后的 redis.conf）
      - ./conf/redis.conf:/home/hata/redis/redis.conf
      - ./redis/data:/data
    # 3. 启动命令不变，仍加载你的配置文件
    command: redis-server /home/hata/redis/redis.conf
    networks:
      - hata-network

  hata-server:
    container_name: ${CONTAINER_PREFIX}-server
    environment:
      <<: *shared-env
      # 数据库配置（覆盖 .env.docker 中的配置）
      DB_HOST: hata-postgresql
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRESQL_ROOT_NAME}
      DB_PASSWORD: ${POSTGRESQL_ROOT_PASSWORD}
      DB_DATABASE: "hata-service-platform"
      # Redis 配置（覆盖 .env.docker 中的配置）
      REDIS_HOST: hata-redis
      REDIS_PORT: 8761
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASE: 2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: hata-server:latest
    ports:
      - "${SERVER_PORT}:9099"
    volumes:
      - ./hata/logs:/home/hata/logs
      - ./hata/uploadPath:/home/hata/uploadPath
    depends_on:
      - hata-postgresql
      - hata-redis
    networks:
      - hata-network
  
  hata-nginx:
    container_name: ${CONTAINER_PREFIX}-nginx
    # image: nginx
    environment:
      <<: *shared-env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: nginx-dockerfile
    ports:
      - "${NGINX_PORT_1}:8087"
      - "${NGINX_PORT_2}:8085"
    volumes:
      # 方便nginx能访问所有页面资源
      - ./nginx-html:/etc/nginx/html
      - ./dataset:/etc/nginx/dataset
      - ./static_files:/etc/nginx/static_files
      - ./html/dist:/home/hata/projects/hata-ui
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/ssl/ssl.key:/etc/nginx/private.key
      - ./conf/ssl/ssl.cer:/etc/nginx/self-sign.cer
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - hata-server
    networks:
      - hata-network